obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[-0.2, -0.2], [-0.2, 0.2], [0.2, 0.2] ,[0.2, -0.2]]


inflation_radius: .5

cost_scaling_factor: 10.0

observation_sources: laser_scan_sensor 

laser_scan_sensor: {sensor_frame: hokuyo, data_type: 
LaserScan, topic: /robot/laser/scan, marking: true, clearing: true}


# marking - add obstacle information to cost map
# clearing - clear obstacle information to cost map
