dd_robot_skid_steer_controller:
# Position Controllers ---------------------------------------
  joint_r_fwheel_position_controller:
   type: effort_controllers/JointPositionController
   joint: joint_r_fwheel
   pid: {p: 100.0, i: 0.01, d: 10.0}

  joint_r_bwheel_position_controller:
   type: effort_controllers/JointPositionController
   joint: joint_r_bwheel
   pid: {p: 100.0, i: 0.01, d: 10.0}


  joint_l_fwheel_position_controller:
   type: effort_controllers/JointPositionController
   joint: joint_l_fwheel
   pid: {p: 100.0, i: 0.01, d: 10.0}

  joint_l_bwheel_position_controller:
   type: effort_controllers/JointPositionController
   joint: joint_l_bwheel
   pid: {p: 100.0, i: 0.01, d: 10.0}
